### ISSUE TITLE
Use codecov everywhere

### ISSUE THREAD

**Issue by alkino** [BlueBrain/libsonata#124]
Some others projects use codecov: nmodl, CoreNeuron, nrn

Should libsonata use that too instead of coverall?

**Comment by pramodk** [comment]
Both tools do more or less same thing I believe and it's more about the familiarity / preference. In hpc projects we started with codecov but I will let @mgeplf and @wizmer to provide preference here.

**Comment by mgeplf** [comment]
What's the benefit of changing?

The main one is consistency, but are there others?

I tried `codecov` originally, and ran into problems with it, iirc, but that's a few months ago.  I believe that nlohmann's JSON used coverall at the time, so that's what I ended up going with.  From what I remember, there were issues w/ line numbers not being right, branch coverage being wrong due to exceptions - but perhaps those have been fixed.

I looked at https://codecov.io/gh/BlueBrain/nmodl/tree/f103ee251f5dee4ee9a82274f3497d57d53e0e35/src/codegen and it seems that I can't click on the files, for some reason, but I assume that's a config issue?

At the time this was done, it looks like the other repositories didn't have coverage reporting added, so it was an arbitrary decision.

We can also upload both in parallel, if you want to make a PR.

**Comment by mgeplf** [comment]
Any further comments on this @alkino / @pramodk?

**Comment by pramodk** [comment]
> The main one is consistency, but are there others?

I don't think there is any other major reason.

> I looked at https://codecov.io/gh/BlueBrain/nmodl/tree/f103ee251f5dee4ee9a82274f3497d57d53e0e35/src/codegen and it seems that I can't click on the files, for some reason, but I assume that's a config issue?

Yes, IIRC, temporary one.

> We can also upload both in parallel, if you want to make a PR.

IMO, we need both. If coverall is something working and you all are familiar, I think we can just keep it. If someone find any major advantage of one over other then we can switch.
